//Created,  24 May 2017
//Last Edit 29 May 2017

/**
 *  \file camera.hpp
 *  \brief     Interface for the camera
 *  \details   An abstract class representing a generic camera in the space
 *  \author    Davide Pizzolotto
 *  \version   0.1
 *  \date      27 May 2017
 *  \copyright GNU GPLv3
 */


#ifndef __CAMERA_HPP__
#define __CAMERA_HPP__

#include "image_output.hpp"
#include "sampler.hpp"
#include "matrix4.hpp"
#include "ray.hpp"

/**
 * \class Camera camera.hpp "cameras/camera.hpp"
 * \brief An interface for a generic camera
 *
 *  This class represents the implementation of a generic camera positioned
 *  in space. The positioning, reffered as "camera to world space" is done
 *  with the LookAt matrix. Other than the positioning, inside the class there
 *  is the film, an ImageOutput object used to store the rendered picture.
 *
 *  This class exposes a method called createRay, that must be overriden by
 *  the different types of camera that will be implemented
 */
class Camera
{
public:
    
    /** \brief Default constructor
     *
     *  \param[in] position The position of the camera in the space
     *  \param[in] target   The target of the camera in the space
     *  \param[in] up       A normalized vector that represents the up direction
     *  of the camera
     *  \param[in] width    The width of the final image (resolution)
     *  \param[in] height   The height of the final image (resolution)
     *  \param[in] filename The name of the file that will be stored onto the
     *  disk
     */
    Camera(const Point3* position, const Point3* target, const Vec3* up,
           int width, int height, const char* filename);
    
    ///Default destructor
    ~Camera();
    
    
    /** \brief Create a ray from a sample
     *
     *  Given a sample, generated by a sampler, in raster space, this methods
     *  create a ray in world space
     *
     *  \param[in] sample The given sample
     *  \param[out] ray   The output ray
     */
    virtual void createRay(Sample* sample, Ray* ray)const = 0;
    
protected:
    
    ///The matrix used to transform from raster space to world space
    Matrix4 raster2world;
    
    ///The object used to store the values of the pixel and save the image
    ImageOutput film;
};

#endif
