//Created,  28 May 2017
//Last Edit  3 Jul 2017

/**
 *  \file perspective_camera.hpp
 *  \brief     A perspective camera
 *  \details   A camera for generating perspective images
 *  \author    Davide Pizzolotto
 *  \version   0.2
 *  \date      3 Jul 2017
 *  \copyright GNU GPLv3
 */


#ifndef __PERSPECTIVE_CAMERA_HPP__
#define __PERSPECTIVE_CAMERA_HPP__

#include "cameras/camera.hpp"
#include "geometry/point3.hpp"
#include "geometry/vec3.hpp"
#include "geometry/ray.hpp"
#include "samplers/sampler.hpp"

/**
 *  \class PerspectiveCamera
 *  \brief A camera generating a perspective projection
 *
 *  This class represents a camera which produces images exhibiting perspective
 *  projection. In this projection every object becomes smaller, the farther it
 *  is from the camera
 *
 *  The near plane and far plane of the viewing frustum used by this camera
 *  are set to 0.0 and 1000.0 respectively
 */
class PerspectiveCamera : public Camera
{
public:

    /** \brief Default constructor
     *
     *  \param[in] position The position of the camera in world space
     *  \param[in] target   The target of the camera in world space
     *  \param[in] up A normalized vector that represents the up direction of
     *  the camera
     *  \param[in] width The width of the final image (resolution)
     *  \param[in] height The height of the final image (resolution)
     *  \param[in] fov The angle of view in radians
     */
    PerspectiveCamera(const Point3* position, const Point3* target,
                       const Vec3* up, int width, int height, float fov);

    /** \brief Create a ray from a sample
     *
     *  Given a sample, generated by a sampler, in raster space, this methods
     *  creates a ray in world space
     *
     *  \param[in] sample The given sample
     *  \param[out] ray The output ray
     */
    void create_ray(Sample* sample, Ray* ray)const;

private:

    ///The matrix used to transform from raster space to camera space
    Matrix4 raster2camera;
};

#endif
