
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION>0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__>=199901L

                                                                                                                        /* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__>=3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
                                                                                                                        /* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE* yyin, * yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
#define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
#define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        *yy_cp = (yy_hold_char); \
        YY_RESTORE_YY_MORE_OFFSET \
        (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
    FILE* yy_input_file;

    char* yy_ch_buf;        /* input buffer */
    char* yy_buf_pos;        /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
    int yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
    int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

    /* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
    int yy_fill_buffer;

    int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE* yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;        /* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char* yy_c_buf_p = NULL;
static int yy_init = 0;        /* whether we need to initialize */
static int yy_start = 0;    /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart(FILE* input_file);

void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);

YY_BUFFER_STATE yy_create_buffer(FILE* file, int size);

void yy_delete_buffer(YY_BUFFER_STATE b);

void yy_flush_buffer(YY_BUFFER_STATE b);

void yypush_buffer_state(YY_BUFFER_STATE new_buffer);

void yypop_buffer_state(void);

static void yyensure_buffer_stack(void);

static void yy_load_buffer_state(void);

static void yy_init_buffer(YY_BUFFER_STATE b, FILE* file);

#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size);

YY_BUFFER_STATE yy_scan_string(const char* yy_str);

YY_BUFFER_STATE yy_scan_bytes(const char* bytes, int len);

void* yyalloc(yy_size_t);

void* yyrealloc(void*, yy_size_t);

void yyfree(void*);

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
    { \
    if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
        YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
    }
#define yy_set_bol(at_bol) \
    { \
    if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
        YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
    }
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE* yyin = NULL, * yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char* yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state(void);

static yy_state_type yy_try_NUL_trans(yy_state_type current_state);

static int yy_get_next_buffer(void);

static void yynoreturn yy_fatal_error(const char* msg);

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    (yytext_ptr) = yy_bp; \
    yyleng = (int) (yy_cp - yy_bp); \
    (yy_hold_char) = *yy_cp; \
    *yy_cp = '\0'; \
    (yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
{
    flex_int32_t yy_verify;
    flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[464] =
        {0,
         0, 0, 120, 118, 115, 117, 116, 118, 114, 118,
         118, 6, 118, 118, 81, 1, 118, 118, 118, 118,
         118, 118, 99, 118, 118, 118, 118, 118, 118, 111,
         93, 118, 2, 3, 118, 118, 118, 118, 118, 118,
         118, 118, 118, 118, 118, 118, 118, 118, 118, 118,
         118, 118, 111, 93, 4, 5, 115, 0, 84, 0,
         114, 0, 0, 0, 81, 82, 83, 0, 85, 86,
         87, 94, 95, 96, 97, 88, 89, 98, 90, 100,
         101, 102, 103, 104, 105, 106, 91, 107, 92, 108,
         109, 110, 112, 113, 0, 0, 94, 0, 0, 0,

         0, 96, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 100, 0, 0, 0,
         104, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 109, 0,
         0, 0, 0, 37, 0, 0, 0, 0, 0, 84,
         0, 0, 83, 0, 0, 0, 0, 21, 0, 0,
         0, 0, 0, 0, 0, 30, 0, 0, 0, 38,
         0, 65, 0, 0, 0, 0, 0, 55, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 7, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

         0, 0, 0, 0, 0, 11, 50, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         80, 0, 0, 61, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 73, 0, 0, 0, 0, 42, 0, 78, 0,
         0, 9, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 79, 0, 0, 0, 22,
         0, 0, 0, 20, 0, 0, 0, 0, 0, 0,
         0, 63, 0, 66, 0, 0, 0, 0, 0, 0,
         74, 24, 54, 0, 0, 0, 0, 0, 41, 0,

         51, 53, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 44, 0, 39, 45, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 12, 40,
         0, 0, 31, 0, 0, 0, 0, 0, 19, 0,
         52, 13, 0, 0, 0, 0, 0, 62, 0, 0,
         0, 0, 76, 17, 0, 0, 0, 0, 75, 0,
         0, 36, 0, 0, 0, 0, 0, 0, 14, 15,
         0, 0, 59, 0, 0, 67, 77, 0, 0, 0,
         27, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         16, 0, 0, 0, 49, 0, 0, 0, 0, 0,

         64, 0, 0, 25, 0, 72, 47, 26, 0, 33,
         0, 35, 0, 43, 0, 60, 0, 0, 23, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 56,
         0, 0, 29, 0, 0, 57, 0, 0, 8, 0,
         0, 10, 18, 0, 28, 0, 0, 0, 0, 32,
         46, 0, 58, 48, 34, 0, 0, 0, 71, 70,
         69, 68, 0
        };

static const YY_CHAR yy_ec[256] =
        {0,
         1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
         1, 1, 4, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 5, 1, 6, 7, 1, 1, 1, 8, 1,
         1, 1, 9, 10, 11, 12, 1, 13, 14, 15,
         15, 15, 15, 15, 15, 15, 15, 16, 1, 1,
         1, 1, 1, 1, 17, 18, 19, 20, 21, 22,
         23, 24, 25, 1, 26, 27, 28, 29, 30, 31,
         1, 32, 1, 33, 34, 35, 36, 1, 1, 37,
         38, 39, 40, 1, 1, 1, 41, 42, 43, 44,

         45, 46, 47, 48, 49, 1, 50, 51, 52, 53,
         54, 55, 1, 56, 57, 58, 59, 60, 61, 62,
         63, 64, 65, 1, 66, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1
        };

static const YY_CHAR yy_meta[67] =
        {0,
         1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1
        };

static const flex_int16_t yy_base[468] =
        {0,
         0, 0, 603, 604, 65, 604, 604, 62, 0, 61,
         59, 604, 63, 66, 70, 604, 63, 67, 64, 66,
         68, 70, 604, 70, 79, 110, 111, 82, 117, 604,
         604, 92, 604, 604, 120, 135, 131, 87, 88, 129,
         154, 117, 50, 157, 173, 175, 152, 192, 197, 211,
         223, 175, 561, 190, 604, 604, 136, 235, 604, 598,
         0, 129, 250, 247, 263, 278, 267, 287, 604, 604,
         604, 604, 604, 604, 604, 604, 604, 604, 604, 604,
         604, 604, 604, 604, 604, 604, 604, 604, 604, 604,
         604, 604, 604, 604, 551, 554, 555, 548, 534, 543,

         542, 542, 131, 551, 546, 549, 538, 214, 528, 528,
         524, 253, 536, 47, 528, 530, 535, 246, 523, 522,
         527, 522, 524, 518, 517, 252, 518, 516, 253, 515,
         255, 519, 529, 526, 166, 264, 525, 511, 510, 263,
         516, 509, 517, 604, 513, 510, 516, 503, 287, 303,
         314, 314, 317, 501, 516, 506, 502, 604, 499, 508,
         498, 505, 492, 498, 496, 604, 496, 488, 488, 604,
         487, 604, 486, 485, 494, 495, 494, 604, 495, 489,
         486, 275, 494, 491, 488, 480, 482, 482, 604, 475,
         480, 470, 477, 476, 480, 469, 481, 474, 465, 468,

         464, 462, 470, 472, 456, 604, 604, 472, 465, 456,
         452, 451, 140, 463, 458, 453, 446, 446, 452, 448,
         604, 449, 447, 604, 443, 442, 438, 440, 443, 449,
         439, 447, 433, 433, 432, 431, 439, 439, 429, 420,
         425, 604, 426, 436, 429, 431, 604, 437, 604, 423,
         420, 604, 420, 416, 414, 418, 420, 412, 421, 417,
         422, 413, 420, 406, 404, 604, 404, 416, 415, 604,
         400, 405, 408, 604, 405, 408, 409, 405, 408, 393,
         409, 604, 408, 604, 391, 398, 405, 392, 398, 387,
         604, 393, 604, 378, 382, 383, 380, 383, 604, 387,

         604, 604, 390, 383, 386, 391, 386, 381, 372, 376,
         368, 377, 372, 379, 604, 379, 604, 604, 371, 372,
         362, 363, 362, 370, 363, 357, 409, 321, 604, 604,
         357, 359, 604, 366, 368, 351, 350, 361, 604, 365,
         604, 604, 364, 359, 346, 361, 350, 604, 344, 347,
         355, 343, 604, 604, 338, 341, 349, 337, 604, 351,
         345, 604, 349, 344, 337, 342, 341, 342, 604, 604,
         330, 330, 604, 323, 336, 604, 604, 327, 321, 334,
         604, 326, 325, 334, 333, 315, 319, 322, 317, 312,
         604, 312, 318, 308, 604, 320, 323, 307, 314, 306,

         604, 302, 295, 604, 296, 604, 604, 604, 294, 604,
         299, 604, 293, 604, 289, 604, 300, 285, 604, 285,
         295, 298, 273, 275, 272, 231, 237, 223, 220, 604,
         227, 207, 604, 213, 202, 604, 195, 206, 604, 194,
         190, 604, 604, 186, 604, 170, 166, 162, 166, 604,
         604, 152, 604, 604, 604, 106, 120, 320, 604, 604,
         604, 604, 604, 353, 98, 355, 357
        };

static const flex_int16_t yy_def[468] =
        {0,
         463, 1, 463, 463, 463, 463, 463, 464, 465, 466,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 464, 463, 464,
         465, 466, 467, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,

         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 466, 466,
         467, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,

         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,

         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,

         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 0, 463, 463, 463, 463
        };

static const flex_int16_t yy_nxt[671] =
        {0,
         4, 5, 6, 7, 5, 8, 9, 10, 11, 12,
         13, 14, 15, 15, 15, 16, 17, 18, 19, 4,
         4, 20, 21, 22, 4, 23, 24, 25, 26, 4,
         27, 28, 29, 4, 30, 31, 32, 33, 4, 34,
         35, 36, 37, 38, 39, 40, 41, 42, 43, 23,
         44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 4, 4, 32, 55, 56, 57, 59, 59, 57,
         64, 65, 65, 65, 64, 66, 66, 66, 67, 67,
         67, 64, 65, 65, 65, 69, 77, 72, 78, 70,
         68, 73, 79, 74, 80, 75, 71, 76, 61, 63,

         60, 81, 114, 115, 176, 90, 177, 82, 83, 69,
         77, 72, 78, 70, 68, 73, 79, 74, 80, 75,
         93, 71, 76, 94, 458, 81, 84, 85, 87, 90,
         88, 82, 83, 91, 86, 103, 59, 57, 105, 79,
         57, 92, 69, 89, 93, 104, 70, 94, 106, 77,
         84, 85, 87, 71, 88, 72, 457, 91, 86, 73,
         74, 113, 75, 79, 76, 92, 69, 63, 89, 107,
         70, 101, 95, 77, 78, 96, 162, 108, 71, 97,
         272, 80, 109, 73, 102, 98, 75, 163, 99, 76,
         273, 84, 85, 100, 110, 81, 456, 116, 78, 86,

         111, 82, 83, 123, 112, 117, 202, 124, 455, 87,
         125, 88, 454, 118, 203, 121, 85, 119, 453, 81,
         90, 120, 452, 86, 89, 82, 83, 143, 122, 144,
         451, 145, 126, 87, 450, 88, 127, 129, 147, 91,
         59, 130, 449, 148, 90, 128, 448, 92, 447, 89,
         131, 132, 62, 133, 446, 134, 445, 150, 135, 67,
         67, 67, 444, 139, 168, 136, 137, 140, 138, 169,
         443, 92, 442, 60, 64, 65, 65, 65, 141, 67,
         67, 67, 441, 68, 440, 142, 439, 68, 151, 64,
         66, 66, 66, 173, 59, 152, 194, 152, 68, 153,

         153, 153, 181, 182, 190, 195, 174, 68, 204, 191,
         59, 68, 197, 198, 210, 211, 62, 205, 206, 243,
         438, 150, 68, 437, 212, 63, 153, 153, 153, 153,
         153, 153, 244, 369, 370, 436, 459, 460, 435, 434,
         433, 63, 461, 432, 431, 430, 429, 428, 427, 426,
         425, 462, 151, 58, 58, 62, 62, 149, 149, 424,
         423, 422, 421, 420, 419, 418, 417, 416, 415, 414,
         413, 412, 411, 410, 409, 408, 407, 406, 405, 404,
         403, 402, 401, 400, 399, 398, 397, 396, 395, 394,
         393, 392, 391, 390, 389, 388, 387, 386, 385, 384,

         383, 382, 381, 380, 379, 378, 377, 376, 375, 374,
         373, 372, 371, 368, 367, 366, 365, 364, 363, 362,
         361, 360, 359, 358, 357, 356, 355, 354, 353, 352,
         351, 350, 349, 348, 347, 346, 345, 344, 343, 342,
         341, 340, 339, 338, 337, 336, 335, 334, 333, 332,
         331, 330, 329, 328, 327, 326, 325, 324, 323, 322,
         321, 320, 319, 318, 317, 316, 315, 314, 313, 312,
         311, 310, 309, 308, 307, 306, 305, 304, 303, 302,
         301, 300, 299, 298, 297, 296, 295, 294, 293, 292,
         291, 290, 289, 288, 287, 286, 285, 284, 283, 282,

         281, 280, 279, 278, 277, 276, 275, 274, 271, 270,
         269, 268, 267, 266, 265, 264, 263, 262, 261, 260,
         259, 258, 257, 256, 255, 254, 253, 252, 251, 250,
         249, 248, 247, 246, 245, 242, 241, 240, 239, 238,
         237, 236, 235, 234, 233, 232, 231, 230, 229, 228,
         227, 226, 225, 224, 223, 222, 221, 220, 219, 218,
         217, 216, 215, 214, 213, 209, 208, 207, 201, 200,
         199, 196, 193, 192, 189, 188, 187, 186, 185, 184,
         183, 180, 179, 178, 175, 172, 171, 170, 167, 166,
         165, 164, 161, 160, 159, 158, 157, 156, 155, 154,

         463, 146, 463, 3, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463
        };

static const flex_int16_t yy_chk[671] =
        {0,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 5, 8, 10, 5,
         11, 11, 11, 11, 13, 13, 13, 13, 14, 14,
         14, 15, 15, 15, 15, 17, 20, 18, 21, 17,
         15, 18, 22, 19, 24, 19, 17, 19, 465, 10,

         8, 25, 43, 43, 114, 28, 114, 25, 25, 17,
         20, 18, 21, 17, 15, 18, 22, 19, 24, 19,
         32, 17, 19, 32, 457, 25, 26, 26, 27, 28,
         27, 25, 25, 29, 26, 38, 62, 57, 39, 42,
         57, 29, 35, 27, 32, 38, 35, 32, 39, 40,
         26, 26, 27, 35, 27, 36, 456, 29, 26, 36,
         37, 42, 37, 42, 37, 29, 35, 62, 27, 40,
         35, 37, 35, 40, 41, 35, 103, 40, 35, 36,
         213, 44, 40, 36, 37, 36, 37, 103, 36, 37,
         213, 46, 46, 36, 41, 45, 452, 44, 41, 46,

         41, 45, 45, 47, 41, 44, 135, 47, 449, 48,
         47, 48, 448, 45, 135, 46, 46, 45, 447, 45,
         49, 45, 446, 46, 48, 45, 45, 52, 46, 52,
         444, 52, 48, 48, 441, 48, 48, 49, 54, 51,
         58, 49, 440, 54, 49, 48, 438, 51, 437, 48,
         49, 50, 63, 50, 435, 50, 434, 63, 50, 64,
         64, 64, 432, 51, 108, 50, 50, 51, 50, 108,
         431, 51, 429, 58, 65, 65, 65, 65, 51, 67,
         67, 67, 428, 65, 427, 51, 426, 67, 63, 66,
         66, 66, 66, 112, 149, 68, 129, 68, 66, 68,

         68, 68, 118, 118, 126, 129, 112, 65, 136, 126,
         150, 67, 131, 131, 140, 140, 151, 136, 136, 182,
         425, 151, 66, 424, 140, 149, 152, 152, 152, 153,
         153, 153, 182, 328, 328, 423, 458, 458, 422, 421,
         420, 150, 458, 418, 417, 415, 413, 411, 409, 405,
         403, 458, 151, 464, 464, 466, 466, 467, 467, 402,
         400, 399, 398, 397, 396, 394, 393, 392, 390, 389,
         388, 387, 386, 385, 384, 383, 382, 380, 379, 378,
         375, 374, 372, 371, 368, 367, 366, 365, 364, 363,
         361, 360, 358, 357, 356, 355, 352, 351, 350, 349,

         347, 346, 345, 344, 343, 340, 338, 337, 336, 335,
         334, 332, 331, 327, 326, 325, 324, 323, 322, 321,
         320, 319, 316, 314, 313, 312, 311, 310, 309, 308,
         307, 306, 305, 304, 303, 300, 298, 297, 296, 295,
         294, 292, 290, 289, 288, 287, 286, 285, 283, 281,
         280, 279, 278, 277, 276, 275, 273, 272, 271, 269,
         268, 267, 265, 264, 263, 262, 261, 260, 259, 258,
         257, 256, 255, 254, 253, 251, 250, 248, 246, 245,
         244, 243, 241, 240, 239, 238, 237, 236, 235, 234,
         233, 232, 231, 230, 229, 228, 227, 226, 225, 223,

         222, 220, 219, 218, 217, 216, 215, 214, 212, 211,
         210, 209, 208, 205, 204, 203, 202, 201, 200, 199,
         198, 197, 196, 195, 194, 193, 192, 191, 190, 188,
         187, 186, 185, 184, 183, 181, 180, 179, 177, 176,
         175, 174, 173, 171, 169, 168, 167, 165, 164, 163,
         162, 161, 160, 159, 157, 156, 155, 154, 148, 147,
         146, 145, 143, 142, 141, 139, 138, 137, 134, 133,
         132, 130, 128, 127, 125, 124, 123, 122, 121, 120,
         119, 117, 116, 115, 113, 111, 110, 109, 107, 106,
         105, 104, 102, 101, 100, 99, 98, 97, 96, 95,

         60, 53, 3, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463,
         463, 463, 463, 463, 463, 463, 463, 463, 463, 463
        };

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[120] =
        {0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        };

static yy_state_type yy_last_accepting_state;
static char* yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char* yytext;
#line 1 "config_lexer.l"
/* Created   24 Mar 2018 */
/* Last Edit  3 Apr 2018 */
#line 5 "config_lexer.l"

#include <stdlib.h> /* for atof and atoi. They are deprecated because of lack of
                       error handling, but lex ensures no errors */
#include <string.h> /* strncpy used in dequote_and_copy() */
#include "config_parser.tab.h"

#define YY_USER_ACTION yylloc.first_line = yylloc.last_line = yylineno;
long int current_pos;
long int last_line_pos;
long int cur_line;
long int line_pos;

static __inline char* dequote_and_copy(const char* old)
{
    const size_t LEN = strlen(old);
    char* target = (char*)malloc(sizeof(char)*LEN-1); /* -2 char +1 '/0' */
    strncpy(target, old+1, LEN-2);
    target[LEN-2] = 0x0;
    return target;
}

#line 791 "lex.yy.c"
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#line 63 "config_lexer.l"
#define UPDATE_LOC UPDATE_POS;UPDATE_COL
#define UPDATE_COL yylloc.first_column=yylloc.last_column-(int)yyleng;
#define UPDATE_POS current_pos+=(int)yyleng;yylloc.last_column+=(int)yyleng;
#define ZERO_COL yylloc.first_column=1;yylloc.last_column=1;
#line 799 "lex.yy.c"
#line 800 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
                                                                                                                        /* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals(void);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy(void);

int yyget_debug(void);

void yyset_debug(int debug_flag);

YY_EXTRA_TYPE yyget_extra(void);

void yyset_extra(YY_EXTRA_TYPE user_defined);

FILE* yyget_in(void);

void yyset_in(FILE* _in_str);

FILE* yyget_out(void);

void yyset_out(FILE* _out_str);

int yyget_leng(void);

char* yyget_text(void);

int yyget_lineno(void);

void yyset_lineno(int _line_number);

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else

extern int yywrap(void);

#endif
#endif

#ifndef YY_NO_UNPUT

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
                                                                                                                        #ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
                                                                                                                        /* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size) \
    if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
        { \
        int c = '*'; \
        int n; \
        for ( n = 0; n < max_size && \
                 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
            buf[n] = (char) c; \
        if ( c == '\n' ) \
            buf[n++] = (char) c; \
        if ( c == EOF && ferror( yyin ) ) \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
        result = n; \
        } \
    else \
        { \
        errno=0; \
        while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
            { \
            if( errno != EINTR) \
                { \
                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                break; \
                } \
            errno=0; \
            clearerr(yyin); \
            } \
        }\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex(void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
    YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
    yy_state_type yy_current_state;
    char* yy_cp, * yy_bp;
    int yy_act;

    if(!(yy_init))
    {
        (yy_init) = 1;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if(!(yy_start))
            (yy_start) = 1;    /* first start state */

        if(!yyin)
            yyin = stdin;

        if(!yyout)
            yyout = stdout;

        if(!YY_CURRENT_BUFFER)
        {
            yyensure_buffer_stack();
            YY_CURRENT_BUFFER_LVALUE =
                    yy_create_buffer(yyin, YY_BUF_SIZE);
        }

        yy_load_buffer_state();
    }

    {
#line 69 "config_lexer.l"


#line 1018 "lex.yy.c"

        while( /*CONSTCOND*/1)        /* loops until end-of-file is reached */
        {
            yy_cp = (yy_c_buf_p);

            /* Support of yytext. */
            *yy_cp = (yy_hold_char);

            /* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
            yy_bp = yy_cp;

            yy_current_state = (yy_start);
            yy_match:
            do
            {
                YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
                if(yy_accept[yy_current_state])
                {
                    (yy_last_accepting_state) = yy_current_state;
                    (yy_last_accepting_cpos) = yy_cp;
                }
                while(yy_chk[yy_base[yy_current_state]+yy_c] !=
                      yy_current_state)
                {
                    yy_current_state = (int)yy_def[yy_current_state];
                    if(yy_current_state>=464)
                        yy_c = yy_meta[yy_c];
                }
                yy_current_state = yy_nxt[yy_base[yy_current_state]+yy_c];
                ++yy_cp;
            } while(yy_current_state != 463);
            yy_cp = (yy_last_accepting_cpos);
            yy_current_state = (yy_last_accepting_state);

            yy_find_action:
            yy_act = yy_accept[yy_current_state];

            YY_DO_BEFORE_ACTION;

            if(yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act])
            {
                int yyl;
                for(yyl = 0; yyl<yyleng; ++yyl)
                    if(yytext[yyl] == '\n')

                        yylineno++;;
            }

            do_action:    /* This label is used only to access EOF actions. */

            switch(yy_act)
            { /* beginning of action switch */
                case 0: /* must back up */
                    /* undo the effects of YY_DO_BEFORE_ACTION */
                    *yy_cp = (yy_hold_char);
                    yy_cp = (yy_last_accepting_cpos);
                    yy_current_state = (yy_last_accepting_state);
                    goto yy_find_action;

                case 1:YY_RULE_SETUP
#line 71 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return COLON;
                    }
                    YY_BREAK
                case 2:YY_RULE_SETUP
#line 72 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return OPEN_SQ;
                    }
                    YY_BREAK
                case 3:YY_RULE_SETUP
#line 73 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CLOSE_SQ;
                    }
                    YY_BREAK
                case 4:YY_RULE_SETUP
#line 74 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return OPEN_CU;
                    }
                    YY_BREAK
                case 5:YY_RULE_SETUP
#line 75 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CLOSE_CU;
                    }
                    YY_BREAK
                case 6:YY_RULE_SETUP
#line 76 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return COMMA;
                    }
                    YY_BREAK
                case 7:YY_RULE_SETUP
#line 77 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return OUTPUT;
                    }
                    YY_BREAK
                case 8:YY_RULE_SETUP
#line 78 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return INTEGRATOR;
                    }
                    YY_BREAK
                case 9:YY_RULE_SETUP
#line 79 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return PATH_TRACE;
                    }
                    YY_BREAK
                case 10:YY_RULE_SETUP
#line 80 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return RESOLUTION;
                    }
                    YY_BREAK
                case 11:YY_RULE_SETUP
#line 81 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SPP;
                    }
                    YY_BREAK
                case 12:YY_RULE_SETUP
#line 82 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return WIDTH;
                    }
                    YY_BREAK
                case 13:YY_RULE_SETUP
#line 83 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return HEIGHT;
                    }
                    YY_BREAK
                case 14:YY_RULE_SETUP
#line 84 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return VAL_0;
                    }
                    YY_BREAK
                case 15:YY_RULE_SETUP
#line 85 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return VAL_1;
                    }
                    YY_BREAK
                case 16:YY_RULE_SETUP
#line 86 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SAMPLER;
                    }
                    YY_BREAK
                case 17:YY_RULE_SETUP
#line 87 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return RANDOM_TOKEN;
                    }
                    YY_BREAK
                case 18:YY_RULE_SETUP
#line 88 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return STRATIFIED_TOKEN;
                    }
                    YY_BREAK
                case 19:YY_RULE_SETUP
#line 89 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return FILTER;
                    }
                    YY_BREAK
                case 20:YY_RULE_SETUP
#line 90 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TYPE;
                    }
                    YY_BREAK
                case 21:YY_RULE_SETUP
#line 91 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return BOX_TOKEN;
                    }
                    YY_BREAK
                case 22:YY_RULE_SETUP
#line 92 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TENT_TOKEN;
                    }
                    YY_BREAK
                case 23:YY_RULE_SETUP
#line 93 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TENT_TOKEN;
                    }
                    YY_BREAK
                case 24:YY_RULE_SETUP
#line 94 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GAUSS_TOKEN;
                    }
                    YY_BREAK
                case 25:YY_RULE_SETUP
#line 95 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GAUSS_TOKEN;
                    }
                    YY_BREAK
                case 26:YY_RULE_SETUP
#line 96 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MITCHELL_TOKEN;
                    }
                    YY_BREAK
                case 27:YY_RULE_SETUP
#line 97 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return LANCZOS_TOKEN;
                    }
                    YY_BREAK
                case 28:YY_RULE_SETUP
#line 98 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return UNFILTERED_TOKEN;
                    }
                    YY_BREAK
                case 29:YY_RULE_SETUP
#line 99 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TRILINEAR_TOKEN;
                    }
                    YY_BREAK
                case 30:YY_RULE_SETUP
#line 100 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return EWA_TOKEN;
                    }
                    YY_BREAK
                case 31:YY_RULE_SETUP
#line 101 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CAMERA;
                    }
                    YY_BREAK
                case 32:YY_RULE_SETUP
#line 102 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return PERSPECTIVE_TOKEN;
                    }
                    YY_BREAK
                case 33:YY_RULE_SETUP
#line 103 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return PANORAMA_TOKEN;
                    }
                    YY_BREAK
                case 34:YY_RULE_SETUP
#line 104 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ORTHOGRAPHIC_TOKEN;
                    }
                    YY_BREAK
                case 35:YY_RULE_SETUP
#line 105 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return POSITION;
                    }
                    YY_BREAK
                case 36:YY_RULE_SETUP
#line 106 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TARGET;
                    }
                    YY_BREAK
                case 37:YY_RULE_SETUP
#line 107 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return UP;
                    }
                    YY_BREAK
                case 38:YY_RULE_SETUP
#line 108 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return FOV;
                    }
                    YY_BREAK
                case 39:YY_RULE_SETUP
#line 109 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SHAPE;
                    }
                    YY_BREAK
                case 40:YY_RULE_SETUP
#line 110 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return WORLD;
                    }
                    YY_BREAK
                case 41:YY_RULE_SETUP
#line 111 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return LIGHT;
                    }
                    YY_BREAK
                case 42:YY_RULE_SETUP
#line 112 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return NAME;
                    }
                    YY_BREAK
                case 43:YY_RULE_SETUP
#line 113 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ROTATION;
                    }
                    YY_BREAK
                case 44:YY_RULE_SETUP
#line 114 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SCALE;
                    }
                    YY_BREAK
                case 45:YY_RULE_SETUP
#line 115 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SHIFT;
                    }
                    YY_BREAK
                case 46:YY_RULE_SETUP
#line 116 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TEMPERATURE;
                    }
                    YY_BREAK
                case 47:YY_RULE_SETUP
#line 117 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MATERIAL;
                    }
                    YY_BREAK
                case 48:YY_RULE_SETUP
#line 118 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return DUALMATERIAL;
                    }
                    YY_BREAK
                case 49:YY_RULE_SETUP
#line 119 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TEXTURE;
                    }
                    YY_BREAK
                case 50:YY_RULE_SETUP
#line 120 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SRC;
                    }
                    YY_BREAK
                case 51:YY_RULE_SETUP
#line 121 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MATTE_TOKEN;
                    }
                    YY_BREAK
                case 52:YY_RULE_SETUP
#line 122 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GLOSSY_TOKEN;
                    }
                    YY_BREAK
                case 53:YY_RULE_SETUP
#line 123 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return METAL_TOKEN;
                    }
                    YY_BREAK
                case 54:YY_RULE_SETUP
#line 124 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GLASS_TOKEN;
                    }
                    YY_BREAK
                case 55:YY_RULE_SETUP
#line 125 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return IOR;
                    }
                    YY_BREAK
                case 56:YY_RULE_SETUP
#line 126 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ROUGHNESS;
                    }
                    YY_BREAK
                case 57:YY_RULE_SETUP
#line 127 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ANISOTROPY;
                    }
                    YY_BREAK
                case 58:YY_RULE_SETUP
#line 128 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return DISTRIBUTION;
                    }
                    YY_BREAK
                case 59:YY_RULE_SETUP
#line 129 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return DIFFUSE;
                    }
                    YY_BREAK
                case 60:YY_RULE_SETUP
#line 130 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SPECULAR;
                    }
                    YY_BREAK
                case 61:YY_RULE_SETUP
#line 131 "config_lexer.l"
                    {/* UPDATE_LOC; return BUMP; */}
                    YY_BREAK
                case 62:YY_RULE_SETUP
#line 132 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return NORMAL;
                    }
                    YY_BREAK
                case 63:YY_RULE_SETUP
#line 133 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return BLINN_TOKEN;
                    }
                    YY_BREAK
                case 64:YY_RULE_SETUP
#line 134 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return BECKMANN_TOKEN;
                    }
                    YY_BREAK
                case 65:YY_RULE_SETUP
#line 135 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GGX_TOKEN;
                    }
                    YY_BREAK
                case 66:YY_RULE_SETUP
#line 136 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return COLOR;
                    }
                    YY_BREAK
                case 67:YY_RULE_SETUP
#line 137 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ELEM;
                    }
                    YY_BREAK
                case 68:YY_RULE_SETUP
#line 138 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CHNR;
                    }
                    YY_BREAK
                case 69:YY_RULE_SETUP
#line 139 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CHNG;
                    }
                    YY_BREAK
                case 70:YY_RULE_SETUP
#line 140 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CHNB;
                    }
                    YY_BREAK
                case 71:YY_RULE_SETUP
#line 141 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CHNA;
                    }
                    YY_BREAK
                case 72:YY_RULE_SETUP
#line 142 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return INV;
                    }
                    YY_BREAK
                case 73:YY_RULE_SETUP
#line 143 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MASK;
                    }
                    YY_BREAK
                case 74:YY_RULE_SETUP
#line 144 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return FIRST;
                    }
                    YY_BREAK
                case 75:YY_RULE_SETUP
#line 145 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SECOND;
                    }
                    YY_BREAK
                case 76:YY_RULE_SETUP
#line 146 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return RADIUS;
                    }
                    YY_BREAK
                case 77:YY_RULE_SETUP
#line 147 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return FALLOFF;
                    }
                    YY_BREAK
                case 78:YY_RULE_SETUP
#line 148 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return OMNI_TOKEN;
                    }
                    YY_BREAK
                case 79:YY_RULE_SETUP
#line 149 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SPOT_TOKEN;
                    }
                    YY_BREAK
                case 80:YY_RULE_SETUP
#line 150 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return AREA_TOKEN;
                    }
                    YY_BREAK
                case 81:YY_RULE_SETUP
#line 151 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        yylval.uval = atoi(yytext);
                        return UINT;
                    }
                    YY_BREAK
                case 82:YY_RULE_SETUP
#line 152 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        yylval.ival = atoi(yytext);
                        return INT;
                    }
                    YY_BREAK
                case 83:YY_RULE_SETUP
#line 153 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        yylval.fval = atof(yytext);
                        return FLOAT;
                    }
                    YY_BREAK
                case 84:
/* rule 84 can match eol */
                    YY_RULE_SETUP
#line 154 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        yylval.sval = dequote_and_copy(yytext);
                        return STRING;
                    }
                    YY_BREAK
                case 85:YY_RULE_SETUP
#line 155 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SILVER;
                    }
                    YY_BREAK
                case 86:YY_RULE_SETUP
#line 156 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ALUMINIUM;
                    }
                    YY_BREAK
                case 87:YY_RULE_SETUP
#line 157 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GOLD;
                    }
                    YY_BREAK
                case 88:YY_RULE_SETUP
#line 158 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return COPPER;
                    }
                    YY_BREAK
                case 89:YY_RULE_SETUP
#line 159 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return IRON;
                    }
                    YY_BREAK
                case 90:YY_RULE_SETUP
#line 160 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MERCURY;
                    }
                    YY_BREAK
                case 91:YY_RULE_SETUP
#line 161 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return LEAD;
                    }
                    YY_BREAK
                case 92:YY_RULE_SETUP
#line 162 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return PLATINUM;
                    }
                    YY_BREAK
                case 93:YY_RULE_SETUP
#line 163 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TUNGSTEN;
                    }
                    YY_BREAK
                case 94:YY_RULE_SETUP
#line 164 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return BERYLLIUM;
                    }
                    YY_BREAK
                case 95:YY_RULE_SETUP
#line 165 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return BISMUTH;
                    }
                    YY_BREAK
                case 96:YY_RULE_SETUP
#line 166 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return COBALT;
                    }
                    YY_BREAK
                case 97:YY_RULE_SETUP
#line 167 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return CHROMIUM;
                    }
                    YY_BREAK
                case 98:YY_RULE_SETUP
#line 168 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return GERMANIUM;
                    }
                    YY_BREAK
                case 99:YY_RULE_SETUP
#line 169 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return POTASSIUM;
                    }
                    YY_BREAK
                case 100:YY_RULE_SETUP
#line 170 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return LITHIUM;
                    }
                    YY_BREAK
                case 101:YY_RULE_SETUP
#line 171 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MAGNESIUM;
                    }
                    YY_BREAK
                case 102:YY_RULE_SETUP
#line 172 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MANGANESE;
                    }
                    YY_BREAK
                case 103:YY_RULE_SETUP
#line 173 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return MOLYBDENUM;
                    }
                    YY_BREAK
                case 104:YY_RULE_SETUP
#line 174 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return SODIUM;
                    }
                    YY_BREAK
                case 105:YY_RULE_SETUP
#line 175 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return NIOBIUM;
                    }
                    YY_BREAK
                case 106:YY_RULE_SETUP
#line 176 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return NICKEL;
                    }
                    YY_BREAK
                case 107:YY_RULE_SETUP
#line 177 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return PALLADIUM;
                    }
                    YY_BREAK
                case 108:YY_RULE_SETUP
#line 178 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return RHODIUM;
                    }
                    YY_BREAK
                case 109:YY_RULE_SETUP
#line 179 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TANTALUM;
                    }
                    YY_BREAK
                case 110:YY_RULE_SETUP
#line 180 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return TITANIUM;
                    }
                    YY_BREAK
                case 111:YY_RULE_SETUP
#line 181 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return VANADIUM;
                    }
                    YY_BREAK
                case 112:YY_RULE_SETUP
#line 182 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ZINC;
                    }
                    YY_BREAK
                case 113:YY_RULE_SETUP
#line 183 "config_lexer.l"
                    {
                        UPDATE_LOC;
                        return ZIRCONIUM;
                    }
                    YY_BREAK
                case 114:YY_RULE_SETUP
#line 184 "config_lexer.l"
                    { UPDATE_LOC; }
                    YY_BREAK
                case 115:YY_RULE_SETUP
#line 185 "config_lexer.l"
                    { UPDATE_LOC; }
                    YY_BREAK
                case 116:YY_RULE_SETUP
#line 186 "config_lexer.l"
                    {
                        UPDATE_POS;
                        ZERO_COL;
                    }
                    YY_BREAK
                case 117:
/* rule 117 can match eol */
                    YY_RULE_SETUP
#line 187 "config_lexer.l"
                    {
                        UPDATE_POS;
                        ZERO_COL;
                        cur_line++;
                        last_line_pos = current_pos;
                    }
                    YY_BREAK
                case 118:YY_RULE_SETUP
#line 188 "config_lexer.l"
                    { UPDATE_LOC; /*driver.unknown_char(loc,yytext[0]);*/}
                    YY_BREAK
                case YY_STATE_EOF(INITIAL):
#line 189 "config_lexer.l"
                { return END; }
                    YY_BREAK
                case 119:YY_RULE_SETUP
#line 191 "config_lexer.l"
                    ECHO;
                    YY_BREAK
#line 1682 "lex.yy.c"

                case YY_END_OF_BUFFER:
                {
                    /* Amount of text matched not including the EOB char. */
                    int yy_amount_of_matched_text = (int)(yy_cp-(yytext_ptr))-1;

                    /* Undo the effects of YY_DO_BEFORE_ACTION. */
                    *yy_cp = (yy_hold_char);
                    YY_RESTORE_YY_MORE_OFFSET

                    if(YY_CURRENT_BUFFER_LVALUE->yy_buffer_status ==
                       YY_BUFFER_NEW)
                    {
                        /* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
                        (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                        YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                        YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                    }

                    /* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
                    if((yy_c_buf_p)<=
                       &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
                    { /* This was really a NUL. */
                        yy_state_type yy_next_state;

                        (yy_c_buf_p) = (yytext_ptr)+yy_amount_of_matched_text;

                        yy_current_state = yy_get_previous_state();

                        /* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

                        yy_next_state = yy_try_NUL_trans(yy_current_state);

                        yy_bp = (yytext_ptr)+YY_MORE_ADJ;

                        if(yy_next_state)
                        {
                            /* Consume the NUL. */
                            yy_cp = ++(yy_c_buf_p);
                            yy_current_state = yy_next_state;
                            goto yy_match;
                        }

                        else
                        {
                            yy_cp = (yy_last_accepting_cpos);
                            yy_current_state = (yy_last_accepting_state);
                            goto yy_find_action;
                        }
                    }

                    else
                        switch(yy_get_next_buffer())
                        {
                            case EOB_ACT_END_OF_FILE:
                            {
                                (yy_did_buffer_switch_on_eof) = 0;

                                if(yywrap())
                                {
                                    /* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
                                    (yy_c_buf_p) = (yytext_ptr)+YY_MORE_ADJ;

                                    yy_act = YY_STATE_EOF(YY_START);
                                    goto do_action;
                                }

                                else
                                {
                                    if(!(yy_did_buffer_switch_on_eof))
                                        YY_NEW_FILE;
                                }
                                break;
                            }

                            case EOB_ACT_CONTINUE_SCAN:
                                (yy_c_buf_p) =
                                        (yytext_ptr)+yy_amount_of_matched_text;

                                yy_current_state = yy_get_previous_state();

                                yy_cp = (yy_c_buf_p);
                                yy_bp = (yytext_ptr)+YY_MORE_ADJ;
                                goto yy_match;

                            case EOB_ACT_LAST_MATCH:
                                (yy_c_buf_p) =
                                        &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

                                yy_current_state = yy_get_previous_state();

                                yy_cp = (yy_c_buf_p);
                                yy_bp = (yytext_ptr)+YY_MORE_ADJ;
                                goto yy_find_action;
                        }
                    break;
                }

                default: YY_FATAL_ERROR(
                            "fatal flex scanner internal error--no action found");
            } /* end of action switch */
        } /* end of scanning one token */
    } /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer(void)
{
    char* dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
    char* source = (yytext_ptr);
    int number_to_move, i;
    int ret_val;

    if((yy_c_buf_p)>&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)+1])
        YY_FATAL_ERROR(
                "fatal flex scanner internal error--end of buffer missed");

    if(YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0)
    { /* Don't try to fill the buffer, so this is an EOF. */
        if((yy_c_buf_p)-(yytext_ptr)-YY_MORE_ADJ == 1)
        {
            /* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
            return EOB_ACT_END_OF_FILE;
        }

        else
        {
            /* We matched some text prior to the EOB, first
			 * process it.
			 */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int)((yy_c_buf_p)-(yytext_ptr)-1);

    for(i = 0; i<number_to_move; ++i)
        *(dest++) = *(source++);

    if(YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
        /* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

    else
    {
        int num_to_read =
                YY_CURRENT_BUFFER_LVALUE->yy_buf_size-number_to_move-1;

        while(num_to_read<=0)
        { /* Not enough room in the buffer - grow it. */

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

            int yy_c_buf_p_offset =
                    (int)((yy_c_buf_p)-b->yy_ch_buf);

            if(b->yy_is_our_buffer)
            {
                int new_size = b->yy_buf_size*2;

                if(new_size<=0)
                    b->yy_buf_size += b->yy_buf_size/8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char*)
                        /* Include room in for 2 EOB chars. */
                        yyrealloc((void*)b->yy_ch_buf,
                                  (yy_size_t)(b->yy_buf_size+2));
            }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = NULL;

            if(!b->yy_ch_buf)
                YY_FATAL_ERROR(
                        "fatal error - scanner input buffer overflow");

            (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size-
                          number_to_move-1;

        }

        if(num_to_read>YY_READ_BUF_SIZE)
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
                 (yy_n_chars), num_to_read);

        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    if((yy_n_chars) == 0)
    {
        if(number_to_move == YY_MORE_ADJ)
        {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart(yyin);
        }

        else
        {
            ret_val = EOB_ACT_LAST_MATCH;
            YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
                    YY_BUFFER_EOF_PENDING;
        }
    }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    if(((yy_n_chars)+number_to_move)>YY_CURRENT_BUFFER_LVALUE->yy_buf_size)
    {
        /* Extend the array by 50%, plus the number we really need. */
        int new_size = (yy_n_chars)+number_to_move+((yy_n_chars) >> 1);
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char*)yyrealloc(
                (void*)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,
                (yy_size_t)new_size);
        if(!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
            YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
        /* "- 2" to take care of EOB's */
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int)(new_size-2);
    }

    (yy_n_chars) += number_to_move;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)+1] = YY_END_OF_BUFFER_CHAR;

    (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

    return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state(void)
{
    yy_state_type yy_current_state;
    char* yy_cp;

    yy_current_state = (yy_start);

    for(yy_cp = (yytext_ptr)+YY_MORE_ADJ; yy_cp<(yy_c_buf_p); ++yy_cp)
    {
        YY_CHAR yy_c = (*yy_cp?yy_ec[YY_SC_TO_UI(*yy_cp)]:1);
        if(yy_accept[yy_current_state])
        {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos) = yy_cp;
        }
        while(yy_chk[yy_base[yy_current_state]+yy_c] != yy_current_state)
        {
            yy_current_state = (int)yy_def[yy_current_state];
            if(yy_current_state>=464)
                yy_c = yy_meta[yy_c];
        }
        yy_current_state = yy_nxt[yy_base[yy_current_state]+yy_c];
    }

    return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state)
{
    int yy_is_jam;
    char* yy_cp = (yy_c_buf_p);

    YY_CHAR yy_c = 1;
    if(yy_accept[yy_current_state])
    {
        (yy_last_accepting_state) = yy_current_state;
        (yy_last_accepting_cpos) = yy_cp;
    }
    while(yy_chk[yy_base[yy_current_state]+yy_c] != yy_current_state)
    {
        yy_current_state = (int)yy_def[yy_current_state];
        if(yy_current_state>=464)
            yy_c = yy_meta[yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state]+yy_c];
    yy_is_jam = (yy_current_state == 463);

    return yy_is_jam?0:yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
                                                                                                                        #ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )

    yylineno++;
;

	return c;
}
#endif    /* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyrestart(FILE* input_file)
{

    if(!YY_CURRENT_BUFFER)
    {
        yyensure_buffer_stack();
        YY_CURRENT_BUFFER_LVALUE =
                yy_create_buffer(yyin, YY_BUF_SIZE);
    }

    yy_init_buffer(YY_CURRENT_BUFFER, input_file);
    yy_load_buffer_state();
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
{

    /* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
    yyensure_buffer_stack();
    if(YY_CURRENT_BUFFER == new_buffer)
        return;

    if(YY_CURRENT_BUFFER)
    {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    YY_CURRENT_BUFFER_LVALUE = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
    (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state(void)
{
    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
    (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
    yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
    (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yy_create_buffer(FILE* file, int size)
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
    if(!b)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
    b->yy_ch_buf = (char*)yyalloc((yy_size_t)(b->yy_buf_size+2));
    if(!b->yy_ch_buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_is_our_buffer = 1;

    yy_init_buffer(b, file);

    return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
void yy_delete_buffer(YY_BUFFER_STATE b)
{

    if(!b)
        return;

    if(b == YY_CURRENT_BUFFER) /* Not sure if we should pop here. */
        YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE)0;

    if(b->yy_is_our_buffer)
        yyfree((void*)b->yy_ch_buf);

    yyfree((void*)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
static void yy_init_buffer(YY_BUFFER_STATE b, FILE* file)
{
    int oerrno = errno;

    yy_flush_buffer(b);

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if(b != YY_CURRENT_BUFFER)
    {
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

    b->yy_is_interactive = 0;

    errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
void yy_flush_buffer(YY_BUFFER_STATE b)
{
    if(!b)
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if(b == YY_CURRENT_BUFFER)
        yy_load_buffer_state();
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state(YY_BUFFER_STATE new_buffer)
{
    if(new_buffer == NULL)
        return;

    yyensure_buffer_stack();

    /* This block is copied from yy_switch_to_buffer. */
    if(YY_CURRENT_BUFFER)
    {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    /* Only push if top exists. Otherwise, replace top. */
    if(YY_CURRENT_BUFFER)
        (yy_buffer_stack_top)++;
    YY_CURRENT_BUFFER_LVALUE = new_buffer;

    /* copied from yy_switch_to_buffer. */
    yy_load_buffer_state();
    (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state(void)
{
    if(!YY_CURRENT_BUFFER)
        return;

    yy_delete_buffer(YY_CURRENT_BUFFER);
    YY_CURRENT_BUFFER_LVALUE = NULL;
    if((yy_buffer_stack_top)>0)
        --(yy_buffer_stack_top);

    if(YY_CURRENT_BUFFER)
    {
        yy_load_buffer_state();
        (yy_did_buffer_switch_on_eof) = 1;
    }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack(void)
{
    yy_size_t num_to_alloc;

    if(!(yy_buffer_stack))
    {

        /* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
        num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
        (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
                (num_to_alloc*sizeof(struct yy_buffer_state*)
                );
        if(!(yy_buffer_stack))
            YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

        memset((yy_buffer_stack), 0,
               num_to_alloc*sizeof(struct yy_buffer_state*));

        (yy_buffer_stack_max) = num_to_alloc;
        (yy_buffer_stack_top) = 0;
        return;
    }

    if((yy_buffer_stack_top)>=((yy_buffer_stack_max))-1)
    {

        /* Increase the buffer to prepare for a possible push. */
        yy_size_t grow_size = 8 /* arbitrary grow size */;

        num_to_alloc = (yy_buffer_stack_max)+grow_size;
        (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
                ((yy_buffer_stack),
                 num_to_alloc*sizeof(struct yy_buffer_state*)
                );
        if(!(yy_buffer_stack))
            YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

        /* zero only the new slots.*/
        memset((yy_buffer_stack)+(yy_buffer_stack_max), 0,
               grow_size*sizeof(struct yy_buffer_state*));
        (yy_buffer_stack_max) = num_to_alloc;
    }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size)
{
    YY_BUFFER_STATE b;

    if(size<2 ||
       base[size-2] != YY_END_OF_BUFFER_CHAR ||
       base[size-1] != YY_END_OF_BUFFER_CHAR)
        /* They forgot to leave room for the EOB's. */
        return NULL;

    b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
    if(!b)
        YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

    b->yy_buf_size = (int)(size-2);    /* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = NULL;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer(b);

    return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string(const char* yystr)
{

    return yy_scan_bytes(yystr, (int)strlen(yystr));
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes(const char* yybytes, int _yybytes_len)
{
    YY_BUFFER_STATE b;
    char* buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = (yy_size_t)(_yybytes_len+2);
    buf = (char*)yyalloc(n);
    if(!buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

    for(i = 0; i<_yybytes_len; ++i)
        buf[i] = yybytes[i];

    buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer(buf, n);
    if(!b)
        YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

    /* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
    b->yy_is_our_buffer = 1;

    return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error(const char* msg)
{
    fprintf(stderr, "%s\n", msg);
    exit(YY_EXIT_FAILURE);
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        yytext[yyleng] = (yy_hold_char); \
        (yy_c_buf_p) = yytext + yyless_macro_arg; \
        (yy_hold_char) = *(yy_c_buf_p); \
        *(yy_c_buf_p) = '\0'; \
        yyleng = yyless_macro_arg; \
        } \
    while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno(void)
{

    return yylineno;
}

/** Get the input stream.
 *
 */
FILE* yyget_in(void)
{
    return yyin;
}

/** Get the output stream.
 *
 */
FILE* yyget_out(void)
{
    return yyout;
}

/** Get the length of the current token.
 *
 */
int yyget_leng(void)
{
    return yyleng;
}

/** Get the current token.
 *
 */

char* yyget_text(void)
{
    return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 *
 */
void yyset_lineno(int _line_number)
{

    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in(FILE* _in_str)
{
    yyin = _in_str;
}

void yyset_out(FILE* _out_str)
{
    yyout = _out_str;
}

int yyget_debug(void)
{
    return yy_flex_debug;
}

void yyset_debug(int _bdebug)
{
    yy_flex_debug = _bdebug;
}

static int yy_init_globals(void)
{
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno = 1;

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
                                                                                                                            yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy(void)
{

    /* Pop the buffer stack, destroying each element. */
    while(YY_CURRENT_BUFFER)
    {
        yy_delete_buffer(YY_CURRENT_BUFFER);
        YY_CURRENT_BUFFER_LVALUE = NULL;
        yypop_buffer_state();
    }

    /* Destroy the stack itself. */
    yyfree((yy_buffer_stack));
    (yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals();

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
                                                                                                                        static void yy_flex_strncpy (char* s1, const char * s2, int n )
{

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
                                                                                                                        static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void* yyalloc(yy_size_t size)
{
    return malloc(size);
}

void* yyrealloc(void* ptr, yy_size_t size)
{

    /* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
    return realloc(ptr, size);
}

void yyfree(void* ptr)
{
    free((char*)ptr);    /* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 191 "config_lexer.l"


int yywrap(void)
{
    return 1;
}

void config_scan_begin()
{
    errno = 0;
    current_pos = 0;
    last_line_pos = 0;
    cur_line = 1;
    ZERO_COL;
}

/* get a portion of the line being parsed */
int config_get_line(char* buf, int len)
{
    int line_offset = 0;
    int i = 0;
    /*
     * entire line can't fit in buffer
     * -4 because if the line is too long the last 3 chars are set to ... and
     * I don't want to show the underline ~~~~ in these characters
     */
    if(current_pos-last_line_pos>=len-4)
    {
        line_offset = last_line_pos;
        last_line_pos = current_pos-len/2;
        line_offset = last_line_pos-line_offset;
    }
    fseek(yyin, last_line_pos, SEEK_SET);
    fread(buf, sizeof(char), len, yyin);
    while(i<len)
    {
        if(buf[i] == '\n' || buf[i] == '\r')
            buf[i] = 0;
        if(buf[i] == 0)
            break;
        i++;
    }
    if(i == len)
    {
        buf[len-4] = '.';
        buf[len-3] = '.';
        buf[len-2] = '.';
        buf[len-1] = 0;
    }
    if(line_offset != 0)
    {
        buf[0] = '.';
        buf[1] = '.';
        buf[2] = '.';
    }
    return line_offset;
}

