
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[439] =
    {   0,
        0,    0,  113,  111,  109,  110,  111,  108,  111,  111,
        6,  111,  111,   75,    1,  111,  111,  111,  111,  111,
      111,   93,  111,  111,  111,  111,  111,  111,  105,   87,
      111,    2,    3,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  105,   87,    4,    5,    0,   78,    0,  108,    0,
        0,    0,   75,   76,   77,    0,   79,   80,   81,   88,
       89,   90,   91,   82,   83,   92,   84,   94,   95,   96,
       97,   98,   99,  100,   85,  101,   86,  102,  103,  104,
      106,  107,    0,   88,    0,    0,    0,    0,   90,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   94,    0,    0,    0,   98,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  103,    0,    0,    0,    0,   37,    0,    0,
        0,    0,    0,   78,    0,    0,   77,    0,    0,    0,
       21,    0,    0,    0,    0,    0,    0,    0,   30,    0,
        0,   38,    0,   64,    0,    0,    0,    0,    0,   55,
        0,    0,    0,    0,    0,    0,    0,    0,    7,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   11,   50,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       61,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   72,    0,    0,
        0,    0,   42,    0,    0,    9,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   22,    0,    0,    0,   20,    0,    0,    0,    0,
        0,    0,    0,   62,    0,   65,    0,    0,    0,    0,
        0,   73,   24,   54,    0,    0,    0,    0,    0,   41,
        0,   51,   53,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   44,    0,   39,   45,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   12,   40,    0,
        0,   31,    0,    0,    0,    0,   19,    0,   52,   13,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,
        0,    0,    0,    0,   74,    0,    0,   36,    0,    0,
        0,    0,    0,    0,   14,   15,    0,    0,   59,    0,
        0,   66,    0,    0,    0,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,    0,    0,   49,
        0,    0,    0,    0,    0,   63,    0,    0,   25,    0,
       71,   47,   26,    0,   33,    0,   35,    0,   43,    0,
       60,    0,    0,   23,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   56,    0,    0,   29,    0,    0,
       57,    0,    0,    8,    0,    0,   10,   18,    0,   28,
        0,    0,    0,    0,   32,   46,    0,   58,   48,   34,
        0,    0,    0,   70,   69,   68,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    8,    1,
        1,    1,    9,   10,   11,   12,    1,   13,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   29,   30,   31,
        1,   32,    1,   33,   34,   35,   36,    1,    1,   37,
       38,   39,   40,    1,    1,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,
       54,   55,    1,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,    1,   66,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[443] =
    {   0,
        0,    0,  576,  577,  577,  577,   61,    0,   60,   57,
      577,   61,   64,   68,  577,   61,   65,   62,   64,   66,
       68,  577,   68,   75,  106,  107,   78,  113,  577,  577,
      103,  577,  577,  110,  121,  144,   48,   92,  137,  143,
      148,  114,  111,  176,  190,   47,  193,  195,  205,  227,
      124,  534,   85,  577,  577,  144,  577,  571,    0,  165,
      189,  241,  252,  265,  274,  285,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  524,  529,  522,  508,  517,  516,  516,  155,

      525,  520,  523,  158,  503,  503,  499,  148,  511,  158,
      503,  505,  510,  184,  498,  497,  502,  495,  494,  169,
      495,  493,  496,  491,  199,  495,  505,  502,  221,  165,
      501,  487,  486,  222,  492,  485,  493,  577,  489,  486,
      492,  479,  263,  273,  298,  278,  290,  477,  483,  479,
      577,  476,  485,  475,  482,  469,  475,  473,  577,  466,
      466,  577,  465,  577,  464,  463,  472,  473,  472,  577,
      473,  467,  464,  224,  472,  469,  466,  462,  577,  455,
      460,  450,  457,  461,  450,  462,  455,  446,  449,  445,
      443,  451,  453,  577,  577,  454,  447,  438,  434,  433,

      266,  445,  440,  435,  428,  428,  434,  430,  431,  429,
      577,  425,  424,  420,  422,  425,  431,  430,  416,  416,
      415,  414,  422,  422,  412,  403,  408,  577,  409,  419,
      412,  414,  577,  407,  404,  577,  404,  400,  403,  405,
      397,  406,  402,  407,  398,  405,  391,  389,  389,  401,
      400,  577,  385,  390,  393,  577,  390,  393,  394,  390,
      393,  378,  394,  577,  393,  577,  376,  383,  390,  377,
      373,  577,  379,  577,  364,  368,  369,  366,  369,  577,
      373,  577,  577,  376,  373,  378,  373,  368,  364,  356,
      365,  360,  367,  577,  367,  577,  577,  359,  360,  350,

      351,  350,  358,  351,  345,  397,  295,  577,  577,  345,
      347,  577,  354,  356,  339,  338,  577,  354,  577,  577,
      353,  348,  335,  350,  339,  333,  336,  344,  332,  577,
      327,  330,  338,  326,  577,  340,  334,  577,  338,  333,
      326,  331,  330,  331,  577,  577,  319,  319,  577,  312,
      325,  577,  316,  310,  323,  577,  315,  314,  323,  322,
      304,  308,  311,  306,  301,  577,  301,  307,  297,  577,
      309,  312,  296,  303,  295,  577,  291,  292,  577,  293,
      577,  577,  577,  291,  577,  296,  577,  290,  577,  279,
      577,  290,  275,  577,  277,  287,  290,  267,  279,  278,

      270,  277,  264,  270,  577,  278,  265,  577,  274,  263,
      577,  259,  270,  577,  236,  214,  577,  577,  200,  577,
      180,  171,  145,  144,  577,  577,  100,  577,  577,  577,
       90,  114,  297,  577,  577,  577,  577,  577,  337,  100,
      339,  341
    } ;

static const flex_int16_t yy_def[443] =
    {   0,
      438,    1,  438,  438,  438,  438,  439,  440,  441,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  439,  438,  439,  440,  441,
      442,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  441,  441,  442,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,    0,  438,  438,
      438,  438
    } ;

static const flex_int16_t yy_nxt[644] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   14,   14,   15,   16,   17,   18,    4,
        4,   19,   20,   21,    4,   22,   23,   24,   25,    4,
       26,   27,   28,    4,   29,   30,   31,   32,    4,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   22,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,    4,    4,   31,   54,   55,   57,   57,   62,   63,
       63,   63,   62,   64,   64,   64,   65,   65,   65,   62,
       63,   63,   63,   67,   75,   70,   76,   68,   66,   71,
       77,   72,   78,   73,   69,   74,  100,   79,   61,   58,

       59,   88,  118,   80,   81,  119,  101,   67,   75,   70,
       76,   68,   66,   71,   77,   72,   78,   73,  433,   69,
       74,   79,   82,   83,   85,   88,   86,   80,   81,   89,
       84,   91,   67,  141,   92,   78,   68,   90,  142,   87,
      432,   70,  102,   69,  431,   71,   82,   83,   85,   57,
       86,  112,  103,   89,   84,   91,   67,   75,   92,  113,
       68,   90,   93,   76,   87,   94,  110,  111,   69,   71,
       77,   95,   57,   72,   96,   73,  137,   74,  138,   97,
      139,   75,   58,  106,   98,  104,  430,   76,  165,  107,
      105,   60,  109,  108,   77,  429,  144,   99,   79,   73,

      155,  166,   74,   61,   80,   81,   82,   83,  160,  193,
       85,  156,   86,  161,   84,  168,  114,  169,   88,  194,
      115,  180,   79,  428,  116,   87,  181,  145,   80,   81,
      117,   83,  427,  120,   85,  123,   86,  121,   84,  124,
      173,  174,   88,   89,  426,  126,  122,  127,  125,  128,
       87,   90,  129,   65,   65,   65,  186,  187,  425,  130,
      131,  191,  132,   62,   63,   63,   63,  133,  229,  192,
       57,  134,   66,  198,  199,   90,   62,   64,   64,   64,
       57,  230,  135,  200,  424,   66,   65,   65,   65,  136,
      147,  147,  147,  146,   66,  146,   66,  147,  147,  147,

       60,   61,  147,  147,  147,  144,  254,  345,  346,   66,
      423,   61,  422,  434,  435,  421,  255,  420,   66,  436,
      419,  418,  417,  416,  415,  414,  413,  412,  437,  411,
      410,  409,  408,  407,  406,  405,  145,   56,   56,   60,
       60,  143,  143,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,

      347,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,

      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  197,  196,  195,  190,  189,  188,  185,  184,  183,
      182,  179,  178,  177,  176,  175,  172,  171,  170,  167,
      164,  163,  162,  159,  158,  157,  154,  153,  152,  151,
      150,  149,  148,  438,  140,  438,    3,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438
    } ;

static const flex_int16_t yy_chk[644] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    9,   10,   10,
       10,   10,   12,   12,   12,   12,   13,   13,   13,   14,
       14,   14,   14,   16,   19,   17,   20,   16,   14,   17,
       21,   18,   23,   18,   16,   18,   37,   24,    9,    7,

      440,   27,   46,   24,   24,   46,   37,   16,   19,   17,
       20,   16,   14,   17,   21,   18,   23,   18,  432,   16,
       18,   24,   25,   25,   26,   27,   26,   24,   24,   28,
       25,   31,   34,   53,   31,   43,   34,   28,   53,   26,
      431,   35,   38,   34,  427,   35,   25,   25,   26,   56,
       26,   43,   38,   28,   25,   31,   34,   39,   31,   43,
       34,   28,   34,   40,   26,   35,   42,   42,   34,   35,
       41,   35,   60,   36,   35,   36,   51,   36,   51,   35,
       51,   39,   56,   40,   36,   39,  424,   40,  108,   40,
       39,   61,   41,   40,   41,  423,   61,   36,   44,   36,

      100,  108,   36,   60,   44,   44,   45,   45,  104,  130,
       47,  100,   47,  104,   45,  110,   44,  110,   48,  130,
       44,  120,   44,  422,   44,   47,  120,   61,   44,   44,
       45,   45,  421,   47,   47,   48,   47,   47,   45,   48,
      114,  114,   48,   50,  419,   49,   47,   49,   48,   49,
       47,   50,   49,   62,   62,   62,  125,  125,  416,   49,
       49,  129,   49,   63,   63,   63,   63,   50,  174,  129,
      143,   50,   63,  134,  134,   50,   64,   64,   64,   64,
      144,  174,   50,  134,  415,   64,   65,   65,   65,   50,
      146,  146,  146,   66,   65,   66,   63,   66,   66,   66,

      145,  143,  147,  147,  147,  145,  201,  307,  307,   64,
      413,  144,  412,  433,  433,  410,  201,  409,   65,  433,
      407,  406,  404,  403,  402,  401,  400,  399,  433,  398,
      397,  396,  395,  393,  392,  390,  145,  439,  439,  441,
      441,  442,  442,  388,  386,  384,  380,  378,  377,  375,
      374,  373,  372,  371,  369,  368,  367,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  355,  354,  353,  351,
      350,  348,  347,  344,  343,  342,  341,  340,  339,  337,
      336,  334,  333,  332,  331,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  318,  316,  315,  314,  313,  311,

      310,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      295,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  281,  279,  278,  277,  276,  275,  273,  271,  270,
      269,  268,  267,  265,  263,  262,  261,  260,  259,  258,
      257,  255,  254,  253,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  235,
      234,  232,  231,  230,  229,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      200,  199,  198,  197,  196,  193,  192,  191,  190,  189,

      188,  187,  186,  185,  184,  183,  182,  181,  180,  178,
      177,  176,  175,  173,  172,  171,  169,  168,  167,  166,
      165,  163,  161,  160,  158,  157,  156,  155,  154,  153,
      152,  150,  149,  148,  142,  141,  140,  139,  137,  136,
      135,  133,  132,  131,  128,  127,  126,  124,  123,  122,
      121,  119,  118,  117,  116,  115,  113,  112,  111,  109,
      107,  106,  105,  103,  102,  101,   99,   98,   97,   96,
       95,   94,   93,   58,   52,    3,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config_lexer.l"
/* Created   24 Mar 2018 */
/* Last Edit  3 Apr 2018 */
#line 5 "config_lexer.l"
#include <cstdlib> //for atof and atoi. They are deprecated because of lack of
                      //error handling, but lex ensures no errors
#include <climits>
#include <cerrno>
#include <string>
#include <cstring>
#include "parsers/config_parser.tab.hh"
#include "parsers/config_driver.hpp"
#undef yywrap
#define yywrap() 1
static yy::location loc;
long int current_pos;
long int last_line_pos;
#line 749 "lex.yy.c"
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#line 59 "config_lexer.l"
    #define YY_USER_ACTION loc.columns(yyleng);
    #define UPDATE_POS current_pos+=strlen(yytext)
#line 755 "lex.yy.c"
#line 756 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 63 "config_lexer.l"



#line 67 "config_lexer.l"
    loc.step();

#line 978 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 439 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 438 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 69 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_COLON(loc); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_OPEN_SQ(loc); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_CLOSE_SQ(loc); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_OPEN_CU(loc); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_CLOSE_CU(loc); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_COMMA(loc); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_OUTPUT(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_INTEGRATOR(loc); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_PATH_TRACE(loc); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_RESOLUTION(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_SPP(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_WIDTH(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_HEIGHT(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_VAL_0(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_VAL_1(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_SAMPLER(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_RANDOM(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_STRATIFIED(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_FILTER(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TYPE(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_BOX(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TENT(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TENT(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_GAUSS(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_GAUSS(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_MITCHELL(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_LANCZOS(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_UNFILTERED(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TRILINEAR(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_EWA(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_CAMERA(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_PERSPECTIVE(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_PANORAMA(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_ORTHOGRAPHIC(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_POSITION(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_TARGET(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 105 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_UP(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_FOV(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 107 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_SHAPE(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 108 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_WORLD(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 109 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_LIGHT(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 110 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_NAME(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 111 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_ROTATION(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_SCALE(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_SHIFT(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 114 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TEMPERATURE(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_MATERIAL(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 116 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_DUALMATERIAL(loc);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 117 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TEXTURE(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_SRC(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_MATTE(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_GLOSSY(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_METAL(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_GLASS(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_IOR(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_ROUGHNESS(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_ANISOTROPY(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_DISTRIBUTION(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_DIFFUSE(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_SPECULAR(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 129 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_BUMP(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_BLINN(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_BECKMANN(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_GGX(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_COLOR(loc);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_ELEM(loc);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_CHNR(loc);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_CHNG(loc);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_CHNB(loc);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_CHNA(loc);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 139 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_INV(loc);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 140 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_MASK(loc);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_FIRST(loc);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 142 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_SECOND(loc);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_UINT(atoi(yytext),loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 144 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_INT(atoi(yytext),loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 145 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_FLOAT(atof(yytext),loc); }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 146 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_STRING(yytext,loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 147 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_SILVER(loc);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 148 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_ALUMINIUM(loc);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 149 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_GOLD(loc);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 150 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_COPPER(loc);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_IRON(loc);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_MERCURY(loc);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_LEAD(loc);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_PLATINUM(loc);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_TUNGSTEN(loc);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_BERYLLIUM(loc);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_BISMUTH(loc);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_COBALT(loc);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_CHROMIUM(loc);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 160 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_GERMANIUM(loc);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 161 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_POTASSIUM(loc);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 162 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_LITHIUM(loc);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 163 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_MAGNESIUM(loc);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 164 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_MANGANESE(loc);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 165 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_MOLYBDENUM(loc);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 166 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_SODIUM(loc);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 167 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_NIOBIUM(loc);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 168 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_NICKEL(loc);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 169 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_PALLADIUM(loc);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 170 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_RHODIUM(loc);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 171 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_TANTALUM(loc);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 172 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_TITANIUM(loc);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 173 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_VANADIUM(loc);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 174 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_ZINC(loc);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 175 "config_lexer.l"
{UPDATE_POS; return yy::ConfigParser::make_ZIRCONIUM(loc);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 176 "config_lexer.l"
{UPDATE_POS; loc.step();}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 177 "config_lexer.l"
{UPDATE_POS; loc.step();}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 178 "config_lexer.l"
{UPDATE_POS; loc.lines(yyleng);loc.step(); last_line_pos=current_pos; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 179 "config_lexer.l"
{UPDATE_POS; driver.unknown_char(loc,yytext[0]);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 180 "config_lexer.l"
{ UPDATE_POS; return yy::ConfigParser::make_END(loc); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 182 "config_lexer.l"
ECHO;
	YY_BREAK
#line 1597 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 439 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 439 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 438);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 182 "config_lexer.l"


void ConfigDriver::scan_begin()
{
    errno = 0;
    current_pos = 0;
    last_line_pos = 0;
    yyin = fopen(file.c_str(), "r");
    if(!yyin)
        Console.critical(MESSAGE_INPUT_ERROR,file.c_str(),strerror(errno));
}

void ConfigDriver::scan_end()
{
    fclose(yyin);
}

int ConfigDriver::get_line(char* buf,int len)
{
    int line_offset = 0;
    //entire line can't fit in buffer
    //-4 because if the line is too long the last 3 chars are set to ... and
    //I don't want to show the underline ~~~~ in these characters
    if(current_pos-last_line_pos>=len-4)
    {
        line_offset = last_line_pos;
        last_line_pos = current_pos - len/2;
        line_offset = last_line_pos-line_offset;
    }
    fseek(yyin,last_line_pos,SEEK_SET);
    fread(buf,sizeof(char),len,yyin);
    int i = 0;
    while(i<len)
    {
        if(buf[i]=='\n' || buf[i]=='\r')
            buf[i] = 0;
        if(buf[i]==0)
            break;
        i++;
    }
    if(i==len)
    {
        buf[len-4] = '.';
        buf[len-3] = '.';
        buf[len-2] = '.';
        buf[len-1] = 0;
    }
    if(line_offset!=0)
    {
        buf[0] = '.';
        buf[1] = '.';
        buf[2] = '.';
    }
    return line_offset;
}

