
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 128
#define YY_END_OF_BUFFER 129
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[484] =
    {   0,
        0,    0,  129,  127,  124,  126,  125,  127,  123,  127,
      127,    6,  127,  127,   90,    1,   73,   72,  127,  127,
       71,  127,  108,  127,  127,  127,  127,   70,  127,  120,
      102,  127,    2,    3,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  120,  102,    4,    5,  124,    0,   93,    0,
      123,    0,    0,    0,   90,   91,   92,    0,   94,   95,
       96,  103,  104,  105,  106,   97,   98,  107,   99,  109,
      110,  111,  112,  113,  114,  115,  100,  116,  101,  117,
      118,  119,  121,  122,    0,    0,  103,    0,    0,    0,

        0,    0,  105,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  109,    0,    0,
        0,    0,  113,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  118,    0,  119,    0,    0,    0,   37,    0,
        0,    0,    0,   93,    0,    0,   92,    0,    0,    0,
        0,   21,    0,    0,    0,    0,    0,    0,    0,    0,
       30,    0,    0,    0,   38,    0,   66,    0,    0,    0,
        0,    0,   56,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       42,    0,    0,   11,   51,    0,   85,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       84,    0,    0,   62,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   77,    0,    0,    0,
        0,   43,    0,   82,    0,    0,    9,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       83,    0,    0,    0,   22,    0,   86,    0,    0,   75,
       20,    0,    0,    0,    0,    0,    0,   64,    0,    0,

       67,    0,    0,    0,    0,    0,    0,   76,    0,   78,
       24,   55,    0,    0,    0,    0,    0,    0,   41,    0,
        0,   52,   54,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   45,    0,   39,   46,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   12,   40,
        0,    0,   31,    0,    0,    0,    0,    0,    0,    0,
       19,    0,   53,   13,    0,    0,    0,    0,    0,    0,
        0,   63,    0,    0,    0,    0,   80,   17,    0,    0,
        0,    0,   79,    0,    0,   36,    0,    0,    0,    0,
        0,   14,   15,    0,    0,   69,   60,    0,    0,   68,

        0,   81,    0,    0,    0,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   16,    0,    0,
        0,   50,    0,    0,    0,    0,   65,    0,    0,    0,
       25,    0,   74,   87,    0,   48,   26,    0,   33,    0,
       35,    0,   44,    0,   61,    0,    0,   23,    0,    0,
        0,    0,    0,   89,    0,   88,    0,    0,    0,   57,
        0,    0,   29,    0,   58,    0,    0,    8,    0,    0,
       10,   18,    0,   28,    0,    0,    0,   32,   47,   59,
       49,   34,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    1,    8,    9,   10,   11,    1,   12,   13,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,    1,
        1,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
        1,   31,    1,   32,   33,   34,   35,    1,    1,   36,
       37,   38,   39,    1,    1,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,
       53,   54,    1,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,    1,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[488] =
    {   0,
        0,    0,  619,  620,  616,  620,  620,   61,    0,   60,
       57,  620,   61,   64,   68,  620,   61,   65,   62,   64,
       66,   68,  620,   68,   75,  106,  107,   78,  113,  620,
      620,  103,  620,  620,  110,  125,  141,   48,   91,  147,
      157,   96,  127,  158,  164,  197,  108,  203,  179,  215,
      237,   48,  577,   85,  620,  620,  614,  147,  620,  612,
        0,  177,  202,  215,  254,  275,  270,  292,  620,  620,
      620,  620,  620,  620,  620,  620,  620,  620,  620,  620,
      620,  620,  620,  620,  620,  620,  620,  620,  620,  620,
      620,  620,  620,  620,  566,  569,  570,  563,  549,  558,

      557,  567,  556,  180,  565,  560,  563,  552,  121,  542,
      542,  538,  104,  550,  174,  542,  182,  550,  543,  133,
      537,  536,  541,  536,  538,  532,  531,  197,  532,  530,
      199,  529,  218,  533,  543,  540,  223,  519,  257,  538,
      524,  526,  522,  242,  525,  200,  521,  529,  620,  523,
      529,  516,  271,  284,  305,  303,  311,  514,  529,  519,
      515,  620,  512,  521,  512,  510,  517,  504,  510,  262,
      620,  168,  502,  502,  620,  501,  620,  500,  499,  508,
      509,  508,  620,  509,  502,  502,  502,  498,  263,  506,
      503,  500,  492,  494,  494,  620,  487,  492,  482,  489,

      488,  492,  481,  493,  486,  477,  480,  476,  474,  482,
      620,  484,  468,  620,  620,  484,  620,  477,  468,  464,
      463,  475,  278,  474,  473,  468,  457,  457,  463,  459,
      620,  460,  458,  620,  454,  456,  452,  448,  450,  453,
      459,  462,  448,  456,  455,  441,  441,  440,  439,  447,
      447,  437,  428,  433,  432,  440,  620,  432,  442,  435,
      437,  620,  443,  620,  429,  426,  620,  426,  422,  420,
      424,  426,  418,  427,  423,  428,  419,  426,  412,  410,
      620,  410,  422,  421,  620,  406,  620,  411,  414,  620,
      620,  411,  416,  412,  415,  400,  416,  620,  415,  410,

      620,  397,  404,  411,  398,  392,  403,  620,  392,  620,
      398,  620,  383,  387,  388,  385,  388,  382,  620,  382,
      390,  620,  620,  393,  386,  389,  394,  389,  384,  375,
      379,  371,  380,  375,  382,  620,  382,  620,  620,  374,
      375,  365,  366,  365,  373,  366,  360,  267,  620,  620,
      361,  363,  620,  364,  369,  371,  354,  353,  361,  363,
      620,  367,  620,  620,  366,  361,  348,  360,  344,  361,
      350,  620,  344,  347,  355,  343,  620,  620,  338,  341,
      349,  337,  620,  351,  345,  620,  349,  344,  337,  342,
      341,  620,  620,  331,  331,  620,  620,  324,  337,  620,

      327,  620,  327,  321,  334,  620,  332,  332,  324,  323,
      332,  331,  313,  317,  320,  315,  310,  620,  310,  316,
      306,  620,  318,  321,  305,  305,  620,  301,  302,  304,
      620,  302,  620,  620,  310,  620,  620,  299,  620,  304,
      620,  298,  620,  294,  620,  298,  283,  620,  285,  295,
      276,  289,  288,  620,  280,  620,  287,  274,  280,  620,
      288,  275,  620,  286,  620,  274,  286,  620,  249,  252,
      620,  620,  208,  620,  189,  180,   93,  620,  620,  620,
      620,  620,  620,  343,  104,  345,  347
    } ;

static const flex_int16_t yy_def[488] =
    {   0,
      483,    1,  483,  483,  483,  483,  483,  484,  485,  486,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  484,  483,  484,
      485,  486,  487,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  486,  486,  487,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,    0,  483,  483,  483,  483
    } ;

static const flex_int16_t yy_nxt[686] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   15,   15,   16,   17,   18,   19,    4,    4,
       20,   21,   22,    4,   23,   24,   25,   26,    4,   27,
       28,   29,    4,   30,   31,   32,   33,    4,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   23,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
        4,    4,   32,   55,   56,   59,   59,   64,   65,   65,
       65,   64,   66,   66,   66,   67,   67,   67,   64,   65,
       65,   65,   69,   77,   72,   78,   70,   68,   73,   79,
       74,   80,   75,   71,   76,  104,   81,   63,   60,  148,

       90,  149,   82,   83,   61,  105,   69,   77,   72,   78,
       70,   68,   73,   79,   74,   80,   75,   79,   71,   76,
       81,   84,   85,   87,   90,   88,   82,   83,   91,   86,
       93,   69,  151,   94,  482,   70,   92,  152,   89,  114,
      106,   79,   71,  178,   72,   84,   85,   87,   73,   88,
      107,   59,   91,   86,   93,   69,  179,   94,  125,   70,
       92,   95,  126,   89,   96,  127,   77,   71,   97,   74,
      173,   75,   73,   76,   98,  174,   78,   99,  115,  116,
      101,   80,  100,   59,   60,   81,  108,  102,  188,  189,
       77,   82,   83,  103,  109,   75,  111,  117,   76,  110,

       78,   90,  112,  120,   62,  118,  113,  121,  154,   81,
      119,  122,   84,   85,   63,   82,   83,  243,  131,   87,
       86,   88,  132,  244,  167,   90,   67,   67,   67,  481,
      181,  133,  182,  184,   89,  168,  123,   85,  185,  155,
      480,  201,  128,   87,   86,   88,  129,  223,  197,  124,
      202,  479,   91,  198,  134,  130,  135,  224,  136,   89,
       92,  137,  209,  138,   64,   65,   65,   65,  139,  140,
      210,  141,  142,   68,  204,  205,  143,   59,  392,  393,
      144,   67,   67,   67,  145,   64,   66,   66,   66,   68,
       59,  146,  219,  220,   68,  478,  477,   68,  147,  156,

      212,  156,  221,  157,  157,  157,  258,   62,   63,  213,
      214,  154,  241,   68,  157,  157,  157,  288,   68,  259,
      242,   63,  157,  157,  157,  476,  475,  289,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  155,   58,   58,   62,   62,  153,  153,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,
      449,  448,  447,  446,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,

      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,

      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  222,  218,  217,  216,  215,
      211,  208,  207,  206,  203,  200,  199,  196,  195,  194,
      193,  192,  191,  190,  187,  186,  183,  180,  177,  176,

      175,  172,  171,  170,  169,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  483,   57,  150,   57,  483,    3,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483
    } ;

static const flex_int16_t yy_chk[686] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   10,   11,   11,   11,
       11,   13,   13,   13,   13,   14,   14,   14,   15,   15,
       15,   15,   17,   20,   18,   21,   17,   15,   18,   22,
       19,   24,   19,   17,   19,   38,   25,   10,    8,   52,

       28,   52,   25,   25,  485,   38,   17,   20,   18,   21,
       17,   15,   18,   22,   19,   24,   19,   42,   17,   19,
       25,   26,   26,   27,   28,   27,   25,   25,   29,   26,
       32,   35,   54,   32,  477,   35,   29,   54,   27,   42,
       39,   42,   35,  113,   36,   26,   26,   27,   36,   27,
       39,   58,   29,   26,   32,   35,  113,   32,   47,   35,
       29,   35,   47,   27,   35,   47,   40,   35,   36,   37,
      109,   37,   36,   37,   36,  109,   41,   36,   43,   43,
       37,   44,   36,   62,   58,   45,   40,   37,  120,  120,
       40,   45,   45,   37,   40,   37,   41,   44,   37,   40,

       41,   49,   41,   45,   63,   44,   41,   45,   63,   45,
       44,   45,   46,   46,   62,   45,   45,  172,   49,   48,
       46,   48,   49,  172,  104,   49,   64,   64,   64,  476,
      115,   49,  115,  117,   48,  104,   46,   46,  117,   63,
      475,  131,   48,   48,   46,   48,   48,  146,  128,   46,
      131,  473,   51,  128,   50,   48,   50,  146,   50,   48,
       51,   50,  137,   50,   65,   65,   65,   65,   50,   50,
      137,   50,   50,   65,  133,  133,   51,  153,  348,  348,
       51,   67,   67,   67,   51,   66,   66,   66,   66,   67,
      154,   51,  144,  144,   66,  470,  469,   65,   51,   68,

      139,   68,  144,   68,   68,   68,  189,  155,  153,  139,
      139,  155,  170,   67,  156,  156,  156,  223,   66,  189,
      170,  154,  157,  157,  157,  467,  466,  223,  464,  462,
      461,  459,  458,  457,  455,  453,  452,  451,  450,  449,
      447,  446,  155,  484,  484,  486,  486,  487,  487,  444,
      442,  440,  438,  435,  432,  430,  429,  428,  426,  425,
      424,  423,  421,  420,  419,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  405,  404,  403,  401,
      399,  398,  395,  394,  391,  390,  389,  388,  387,  385,
      384,  382,  381,  380,  379,  376,  375,  374,  373,  371,

      370,  369,  368,  367,  366,  365,  362,  360,  359,  358,
      357,  356,  355,  354,  352,  351,  347,  346,  345,  344,
      343,  342,  341,  340,  337,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  321,  320,  318,
      317,  316,  315,  314,  313,  311,  309,  307,  306,  305,
      304,  303,  302,  300,  299,  297,  296,  295,  294,  293,
      292,  289,  288,  286,  284,  283,  282,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      266,  265,  263,  261,  260,  259,  258,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,

      243,  242,  241,  240,  239,  238,  237,  236,  235,  233,
      232,  230,  229,  228,  227,  226,  225,  224,  222,  221,
      220,  219,  218,  216,  213,  212,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      195,  194,  193,  192,  191,  190,  188,  187,  186,  185,
      184,  182,  181,  180,  179,  178,  176,  174,  173,  169,
      168,  167,  166,  165,  164,  163,  161,  160,  159,  158,
      152,  151,  150,  148,  147,  145,  143,  142,  141,  140,
      138,  136,  135,  134,  132,  130,  129,  127,  126,  125,
      124,  123,  122,  121,  119,  118,  116,  114,  112,  111,

      110,  108,  107,  106,  105,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   60,   57,   53,    5,    3,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483,  483,  483,  483,  483,  483,
      483,  483,  483,  483,  483
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[129] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config_lexer.l"
/* Created   24 Mar 2018 */
/* Last Edit  3 Apr 2018 */
#line 5 "config_lexer.l"
#include <stdlib.h> /* for atof and atoi. They are deprecated because of lack of
                       error handling, but lex ensures no errors */
#include <string.h> /* strncpy used in dequote_and_copy() */
#include "config_parser.tab.h"
#define YY_USER_ACTION yylloc.first_line = yylloc.last_line = yylineno;
long int current_pos;
long int last_line_pos;
long int cur_line;
long int line_pos;
static __inline char* dequote_and_copy(const char* old)
{
    const size_t LEN = strlen(old);
    char* target = (char*)malloc(sizeof(char)*LEN-1); /* -2 char +1 '/0' */
    strncpy(target, old+1, LEN-2);
    target[LEN-2] = 0x0;
    return target;
}
#line 801 "lex.yy.c"
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1
#line 63 "config_lexer.l"
    #define UPDATE_LOC UPDATE_POS;UPDATE_COL
    #define UPDATE_COL yylloc.first_column=yylloc.last_column-(int)yyleng;
    #define UPDATE_POS current_pos+=(int)yyleng;yylloc.last_column+=(int)yyleng;
    #define ZERO_COL yylloc.first_column=1;yylloc.last_column=1;
#line 809 "lex.yy.c"
#line 810 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 69 "config_lexer.l"


#line 1028 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 484 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 483 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 71 "config_lexer.l"
{ UPDATE_LOC; return COLON; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "config_lexer.l"
{ UPDATE_LOC; return OPEN_SQ; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "config_lexer.l"
{ UPDATE_LOC; return CLOSE_SQ; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "config_lexer.l"
{ UPDATE_LOC; return OPEN_CU; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "config_lexer.l"
{ UPDATE_LOC; return CLOSE_CU; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "config_lexer.l"
{ UPDATE_LOC; return COMMA; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "config_lexer.l"
{ UPDATE_LOC; return OUTPUT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "config_lexer.l"
{ UPDATE_LOC; return INTEGRATOR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "config_lexer.l"
{ UPDATE_LOC; return PATH_TRACE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "config_lexer.l"
{ UPDATE_LOC; return RESOLUTION; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "config_lexer.l"
{UPDATE_LOC; return SPP; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "config_lexer.l"
{ UPDATE_LOC; return WIDTH; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "config_lexer.l"
{ UPDATE_LOC; return HEIGHT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "config_lexer.l"
{ UPDATE_LOC; return VAL_0; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "config_lexer.l"
{ UPDATE_LOC; return VAL_1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "config_lexer.l"
{ UPDATE_LOC; return SAMPLER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "config_lexer.l"
{ UPDATE_LOC; return RANDOM_TOKEN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "config_lexer.l"
{ UPDATE_LOC; return STRATIFIED_TOKEN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "config_lexer.l"
{ UPDATE_LOC; return FILTER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "config_lexer.l"
{ UPDATE_LOC; return TYPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "config_lexer.l"
{ UPDATE_LOC; return BOX_TOKEN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "config_lexer.l"
{ UPDATE_LOC; return TENT_TOKEN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "config_lexer.l"
{ UPDATE_LOC; return TENT_TOKEN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "config_lexer.l"
{ UPDATE_LOC; return GAUSS_TOKEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 95 "config_lexer.l"
{ UPDATE_LOC; return GAUSS_TOKEN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "config_lexer.l"
{ UPDATE_LOC; return MITCHELL_TOKEN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 97 "config_lexer.l"
{ UPDATE_LOC; return LANCZOS_TOKEN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 98 "config_lexer.l"
{ UPDATE_LOC; return UNFILTERED_TOKEN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "config_lexer.l"
{ UPDATE_LOC; return TRILINEAR_TOKEN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "config_lexer.l"
{UPDATE_LOC; return EWA_TOKEN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 101 "config_lexer.l"
{UPDATE_LOC; return CAMERA; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 102 "config_lexer.l"
{ UPDATE_LOC; return PERSPECTIVE_TOKEN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 103 "config_lexer.l"
{UPDATE_LOC; return PANORAMA_TOKEN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 104 "config_lexer.l"
{ UPDATE_LOC; return ORTHOGRAPHIC_TOKEN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 105 "config_lexer.l"
{UPDATE_LOC; return POSITION; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "config_lexer.l"
{UPDATE_LOC; return TARGET; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "config_lexer.l"
{ UPDATE_LOC; return UP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 108 "config_lexer.l"
{ UPDATE_LOC; return FOV; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "config_lexer.l"
{ UPDATE_LOC; return SHAPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "config_lexer.l"
{ UPDATE_LOC; return WORLD; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "config_lexer.l"
{ UPDATE_LOC; return LIGHT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 112 "config_lexer.l"
{ UPDATE_LOC; return SKY_TOKEN;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 113 "config_lexer.l"
{ UPDATE_LOC; return NAME; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 114 "config_lexer.l"
{ UPDATE_LOC; return ROTATION; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 115 "config_lexer.l"
{ UPDATE_LOC; return SCALE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "config_lexer.l"
{ UPDATE_LOC; return SHIFT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "config_lexer.l"
{ UPDATE_LOC; return TEMPERATURE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 118 "config_lexer.l"
{ UPDATE_LOC; return MATERIAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "config_lexer.l"
{UPDATE_LOC; return DUALMATERIAL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "config_lexer.l"
{ UPDATE_LOC; return TEXTURE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 121 "config_lexer.l"
{UPDATE_LOC; return SRC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 122 "config_lexer.l"
{ UPDATE_LOC; return MATTE_TOKEN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 123 "config_lexer.l"
{ UPDATE_LOC; return GLOSSY_TOKEN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 124 "config_lexer.l"
{ UPDATE_LOC; return METAL_TOKEN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 125 "config_lexer.l"
{ UPDATE_LOC; return GLASS_TOKEN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 126 "config_lexer.l"
{ UPDATE_LOC; return IOR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 127 "config_lexer.l"
{ UPDATE_LOC; return ROUGHNESS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 128 "config_lexer.l"
{ UPDATE_LOC; return ANISOTROPY; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 129 "config_lexer.l"
{ UPDATE_LOC; return DISTRIBUTION; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 130 "config_lexer.l"
{ UPDATE_LOC; return DIFFUSE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 131 "config_lexer.l"
{ UPDATE_LOC; return SPECULAR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "config_lexer.l"
{/* UPDATE_LOC; return BUMP; */}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "config_lexer.l"
{UPDATE_LOC; return NORMAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "config_lexer.l"
{ UPDATE_LOC; return BLINN_TOKEN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 "config_lexer.l"
{ UPDATE_LOC; return BECKMANN_TOKEN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "config_lexer.l"
{ UPDATE_LOC; return GGX_TOKEN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "config_lexer.l"
{UPDATE_LOC; return COLOR;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "config_lexer.l"
{UPDATE_LOC; return ELEM;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "config_lexer.l"
{UPDATE_LOC; return CHANNEL_TOKEN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "config_lexer.l"
{UPDATE_LOC; return CHNR;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "config_lexer.l"
{UPDATE_LOC; return CHNG;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "config_lexer.l"
{UPDATE_LOC; return CHNB;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "config_lexer.l"
{UPDATE_LOC; return CHNA;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "config_lexer.l"
{UPDATE_LOC; return INV;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "config_lexer.l"
{UPDATE_LOC; return TRUE;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "config_lexer.l"
{UPDATE_LOC; return FALSE;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "config_lexer.l"
{UPDATE_LOC; return MASK;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "config_lexer.l"
{UPDATE_LOC; return FIRST;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 149 "config_lexer.l"
{UPDATE_LOC; return SECOND;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "config_lexer.l"
{UPDATE_LOC; return RADIUS;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "config_lexer.l"
{UPDATE_LOC; return FALLOFF;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "config_lexer.l"
{UPDATE_LOC; return OMNI_TOKEN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "config_lexer.l"
{UPDATE_LOC; return SPOT_TOKEN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "config_lexer.l"
{UPDATE_LOC; return AREA_TOKEN;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "config_lexer.l"
{UPDATE_LOC; return SUN_TOKEN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "config_lexer.l"
{UPDATE_LOC; return TIME;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "config_lexer.l"
{UPDATE_LOC; return LATITUDE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "config_lexer.l"
{UPDATE_LOC; return LONGITUDE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "config_lexer.l"
{UPDATE_LOC; return ELEVATION;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "config_lexer.l"
{ UPDATE_LOC; yylval.uval = atoi(yytext); return UINT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "config_lexer.l"
{ UPDATE_LOC; yylval.ival = atoi(yytext); return INT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 "config_lexer.l"
{ UPDATE_LOC; yylval.fval = atof(yytext); return FLOAT; }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 163 "config_lexer.l"
{ UPDATE_LOC; yylval.sval = dequote_and_copy(yytext); return STRING; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "config_lexer.l"
{ UPDATE_LOC; return SILVER;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "config_lexer.l"
{ UPDATE_LOC; return ALUMINIUM;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 166 "config_lexer.l"
{ UPDATE_LOC; return GOLD;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 167 "config_lexer.l"
{ UPDATE_LOC; return COPPER;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 168 "config_lexer.l"
{ UPDATE_LOC; return IRON;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 169 "config_lexer.l"
{ UPDATE_LOC; return MERCURY;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 170 "config_lexer.l"
{ UPDATE_LOC; return LEAD;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 171 "config_lexer.l"
{ UPDATE_LOC; return PLATINUM;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 172 "config_lexer.l"
{ UPDATE_LOC; return TUNGSTEN;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 173 "config_lexer.l"
{UPDATE_LOC; return BERYLLIUM;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 174 "config_lexer.l"
{UPDATE_LOC; return BISMUTH;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 175 "config_lexer.l"
{UPDATE_LOC; return COBALT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "config_lexer.l"
{UPDATE_LOC; return CHROMIUM;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 177 "config_lexer.l"
{UPDATE_LOC; return GERMANIUM;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 178 "config_lexer.l"
{UPDATE_LOC; return POTASSIUM;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 179 "config_lexer.l"
{UPDATE_LOC; return LITHIUM;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 180 "config_lexer.l"
{UPDATE_LOC; return MAGNESIUM;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 181 "config_lexer.l"
{UPDATE_LOC; return MANGANESE;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 182 "config_lexer.l"
{UPDATE_LOC; return MOLYBDENUM;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 183 "config_lexer.l"
{UPDATE_LOC; return SODIUM;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 184 "config_lexer.l"
{UPDATE_LOC; return NIOBIUM;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 185 "config_lexer.l"
{UPDATE_LOC; return NICKEL;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 186 "config_lexer.l"
{UPDATE_LOC; return PALLADIUM;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 187 "config_lexer.l"
{UPDATE_LOC; return RHODIUM;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 188 "config_lexer.l"
{UPDATE_LOC; return TANTALUM;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 189 "config_lexer.l"
{UPDATE_LOC; return TITANIUM;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 190 "config_lexer.l"
{UPDATE_LOC; return VANADIUM;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 191 "config_lexer.l"
{UPDATE_LOC; return ZINC;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 192 "config_lexer.l"
{UPDATE_LOC; return ZIRCONIUM;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 193 "config_lexer.l"
{UPDATE_LOC;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 194 "config_lexer.l"
{UPDATE_LOC;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 195 "config_lexer.l"
{UPDATE_POS; ZERO_COL;}
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 196 "config_lexer.l"
{UPDATE_POS; ZERO_COL; cur_line++; last_line_pos=current_pos; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 197 "config_lexer.l"
{UPDATE_LOC; /*driver.unknown_char(loc,yytext[0]);*/}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 198 "config_lexer.l"
{return END; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 200 "config_lexer.l"
ECHO;
	YY_BREAK
#line 1737 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 484 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 484 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 483);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "config_lexer.l"


int yywrap(void)
{
    return 1;
}

void config_scan_begin()
{
    errno = 0;
    current_pos = 0;
    last_line_pos = 0;
    cur_line = 1;
    ZERO_COL;
}

/* get a portion of the line being parsed */
int config_get_line(char* buf, int len)
{
    int line_offset = 0;
    int i = 0;
    /*
     * entire line can't fit in buffer
     * -4 because if the line is too long the last 3 chars are set to ... and
     * I don't want to show the underline ~~~~ in these characters
     */
    if(current_pos-last_line_pos>=len-4)
    {
        line_offset = last_line_pos;
        last_line_pos = current_pos - len/2;
        line_offset = last_line_pos-line_offset;
    }
    fseek(yyin,last_line_pos,SEEK_SET);
    fread(buf,sizeof(char),len,yyin);
    while(i<len)
    {
        if(buf[i]=='\n' || buf[i]=='\r')
            buf[i] = 0;
        if(buf[i]==0)
            break;
        i++;
    }
    if(i==len)
    {
        buf[len-4] = '.';
        buf[len-3] = '.';
        buf[len-2] = '.';
        buf[len-1] = 0;
    }
    if(line_offset!=0)
    {
        buf[0] = '.';
        buf[1] = '.';
        buf[2] = '.';
    }
    return line_offset;
}

