#ifndef __METALS_H__
#define __METALS_H__

/** Type of metals supported by the renderer */
enum metal_t
{
    METAL_NO_VAL = -1,
    METAL_SILVER = 0,
    METAL_ALUMINIUM,
    METAL_GOLD,
    METAL_COPPER,
    METAL_IRON,
    METAL_MERCURY,
    METAL_LEAD,
    METAL_PLATINUM,
    METAL_TUNGSTEN,
    METAL_BERYLLIUM,
    METAL_BISMUTH,
    METAL_COBALT,
    METAL_CHROMIUM,
    METAL_GERMANIUM,
    METAL_POTASSIUM,
    METAL_LITHIUM,
    METAL_MAGNESIUM,
    METAL_MANGANESE,
    METAL_MOLYBDENUM,
    METAL_SODIUM,
    METAL_NIOBIUM,
    METAL_NICKEL,
    METAL_PALLADIUM,
    METAL_RHODIUM,
    METAL_TANTALUM,
    METAL_TITANIUM,
    METAL_VANADIUM,
    METAL_ZINC,
    METAL_ZIRCONIUM,
    METAL_MAX
};

#endif
